apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: pipelines-hello-world-api
  name: pipelines-hello-world-api
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: pipelines-hello-world-api
    weight: 100