apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipelines-hello-world-api
  name: pipelines-hello-world-api
spec:
  type: ClusterIP
  ports:
    - name: port-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-8081
      protocol: TCP
      port: 8081
      targetPort: 8081
  internalTrafficPolicy: Cluster
  selector:
    app: pipelines-hello-world-api