apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipelines-hello-world-api
  name: pipelines-hello-world-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: pipelines-hello-world-api